<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>uuid</key>
        <string>A6C30F0E-F54E-4482-99E1-030310039FEC</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>begin</key>
                <string>^(\s*)(\%style)</string>
                <key>captures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>invalid.deprecated</string>
                    </dict>
                </dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>source.css</string>
                    </dict>
                </array>
                <key>end</key>
                <string>^(\1$|\n)</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>^(\s*)((\%script)|(\-jsq))</string>
                <key>captures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>invalid.deprecated</string>
                    </dict>
                </dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>source.js</string>
                    </dict>
                </array>
                <key>end</key>
                <string>^(\1$|\n)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>storage.type</string>
                <key>match</key>
                <string>\[ *:[\w\d ]+\]</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.parameter</string>
                <key>match</key>
                <string>(^\s*~\^)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.parameter</string>
                <key>match</key>
                <string>(&amp;\w+[\n=!])</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.parameter</string>
                <key>match</key>
                <string>(~.*\$[\d].*~)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.parameter</string>
                <key>match</key>
                <string>(~[\d\.\w]+~\$[\d])</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.parameter</string>
                <key>match</key>
                <string>(\$[*\d]\.\w+~)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.parameter</string>
                <key>match</key>
                <string>(\$[:#.*\d])</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.parameter</string>
                <key>match</key>
                <string>(\*[:#.@&amp;])</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.parameter</string>
                <key>match</key>
                <string>(\*all\*)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>invalid.hot.mark.w2erb</string>
                <key>match</key>
                <string>^\s*(\&gt;\&gt;.+)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>invalid.hot.mark.w2erb</string>
                <key>match</key>
                <string>^(!(H|hot)!.+)</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>invalid.deprecated</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>^\s*(\^.*)</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>^\s*(?==|-|~) </string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.class.ruby</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>punctuation.terminator.tag.w2erb</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#rubyline</string>
                    </dict>
                </array>
                <key>end</key>
                <string>$</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>^\s*(?:(([-%:#\.])([\w-:]*))|(?=\.|#))</string>
                <key>captures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.tag.w2erb</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>meta.tag.w2erb</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.tag.w2erb</string>
                    </dict>
                </dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>entity.name.name.w2erb</string>
                        <key>match</key>
                        <string>\:[\w-]+</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>entity.name.class.w2erb</string>
                        <key>match</key>
                        <string>\.[\w-]+</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.name.id.w2erb</string>
                        <key>match</key>
                        <string>#[\w-]+</string>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>\{(?=.*\}|.*\|\s*$)</string>
                        <key>name</key>
                        <string>meta.section.attributes.w2erb</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>source.ruby.rails</string>
                            </dict>
                            <dict>
                                <key>include</key>
                                <string>#continuation</string>
                            </dict>
                        </array>
                        <key>end</key>
                        <string>\}|$|^(?!.*\|\s*$)</string>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>\[(?=.*\]|.*\|\s*$)</string>
                        <key>name</key>
                        <string>meta.section.object.w2erb</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>source.ruby.rails</string>
                            </dict>
                            <dict>
                                <key>include</key>
                                <string>#continuation</string>
                            </dict>
                        </array>
                        <key>end</key>
                        <string>\]|$|^(?!.*\|\s*$)</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#rubyline</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>punctuation.terminator.tag.w2erb</string>
                        <key>match</key>
                        <string>/</string>
                    </dict>
                </array>
                <key>end</key>
                <string>$|(?!\.|#|\{|\[|=|-|~|/)</string>
            </dict>
        </array>
        <key>name</key>
        <string>Ruby W2tags</string>
        <key>scopeName</key>
        <string>text.w2erb</string>
        <key>fileTypes</key>
        <array>
            <string>w2erb</string>
            <string>hot</string>
        </array>
        <key>foldingStopMarker</key>
        <string>^\s*$</string>
        <key>foldingStartMarker</key>
        <string>^\s*([-%#\:\.\w\=].*)\s$</string>
        <key>repository</key>
        <dict>
            <key>continuation</key>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.separator.continuation.w2erb</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(\|)\s*\n</string>
            </dict>
            <key>rubyline</key>
            <dict>
                <key>contentName</key>
                <string>source.ruby.embedded.w2erb</string>
                <key>begin</key>
                <string>=|-|~</string>
                <key>endCaptures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.ruby.start-block</string>
                    </dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>source.ruby.embedded.html</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.line.ruby.w2erb</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>comment</key>
                        <string>Hack to let ruby comments work in this context properly</string>
                        <key>name</key>
                        <string>comment.line.number-sign.ruby</string>
                        <key>match</key>
                        <string>#.*$</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>source.ruby.rails</string>
                    </dict>
                    <dict>
                        <key>include</key>
                        <string>#continuation</string>
                    </dict>
                </array>
                <key>end</key>
                <string>((do|\{)( \|[^|]+\|)?)$|$|^(?!.*\|\s*$)</string>
            </dict>
        </dict>
    </dict>
</plist>
